### ISSUE TITLE
"Not required on clients" is untrue?

### ISSUE THREAD

**Issue by Bluberry-Kat** [unascribed/PopcornSmelting#6]
When trying to connect to a server with Popcorn Smelting (as of version 1.5) the player gets a registry mismatch error. The issue is no longer present when the client has the mod installed.

**Comment by exaskye** [comment]
Yeah, I removed it from the Curse description when we discovered this.

**Comment by Bluberry-Kat** [comment]
Yeah, but it's still in the github description, though.
