### ISSUE TITLE
Configurable chance to destroy the smelted item

### ISSUE THREAD

**Issue by TheDeviantCrafter** [unascribed/PopcornSmelting#8]
This looks fun to automate, but it looks like you can make a farm that smelts a thousand items per minute just as easily as one that smelts 5. This makes other furnace options a little underwhelming. 

I'd like to be able to configure a chance to destroy the smelted item. This would make it ideal for cases where you need to smelt a huge number of cheap items, such as mass charcoal production. Furnaces would still be useful.

By default, no items would be destroyed.

**Comment by exaskye** [comment]
Implemented by #9. Thanks, @tcheinen!
